# Generated by Django 3.1.4 on 2020-12-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sie', '0002_auto_20201214_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_indicateur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='projet',
            name='code_projet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='projet',
            name='intitule',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projet',
            name='promoteur',
            field=models.CharField(max_length=100),
        ),
    ]
