# Generated by Django 3.1.4 on 2020-12-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sie', '0003_auto_20201215_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='mesure',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='Sie.mesure'),
        ),
        migrations.AddField(
            model_name='mesure',
            name='categorie_mesure',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='Sie.categoriemesure'),
        ),
        migrations.AddField(
            model_name='projet',
            name='thematique',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.PROTECT, to='Sie.thematique'),
        ),
        migrations.AddField(
            model_name='thematique',
            name='indicateurs',
            field=models.ManyToManyField(blank=True, related_name='thematiques', to='Sie.Indicateur'),
        ),
        migrations.AddField(
            model_name='thematique',
            name='programmes',
            field=models.ManyToManyField(blank=True, related_name='thematiques', to='Sie.Programme'),
        ),
    ]
