# Generated by Django 3.1.4 on 2020-12-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sie', '0004_auto_20201215_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='mesure',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Sie.mesure'),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='categorie_mesure',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Sie.categoriemesure'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='thematique',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Sie.thematique'),
        ),
    ]
